/**:
  ros__parameters:
    zedx:
      size: { width: 640, height: 360 } # [pix]
      focal_length: { x: 254.391622, y: 254.391622 } # [pix]
      center_point: { x: 330.013020833, y: 181.149637858 } # [pix]
