/**:
  ros__parameters:
    zedx:
      size: { width: 640, height: 360 } # [pix]
      focal_length: { x: 246.55866667, y: 246.389 } # [pix]
      center_point: { x: 318.345, y: 186.59033333  } # [pix]

